# Generated by Django 5.2.8 on 2025-11-26 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del Artista"),
                ),
                (
                    "biografia",
                    models.TextField(blank=True, null=True, verbose_name="Biografía"),
                ),
                (
                    "imagen",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="URL de Imagen",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Artista",
                "verbose_name_plural": "Artistas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título del Álbum"),
                ),
                (
                    "fecha_lanzamiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Lanzamiento"
                    ),
                ),
                (
                    "portada",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="URL de Portada",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "artista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albumes",
                        to="admin.artist",
                        verbose_name="Artista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Álbum",
                "verbose_name_plural": "Álbumes",
                "ordering": ["-fecha_lanzamiento"],
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=200, verbose_name="Título de la Canción"
                    ),
                ),
                ("duracion", models.DurationField(verbose_name="Duración")),
                (
                    "archivo_audio",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="canciones/",
                        verbose_name="Archivo de Audio",
                    ),
                ),
                (
                    "imagen",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="URL de Imagen",
                    ),
                ),
                (
                    "fecha_subida",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Subida"
                    ),
                ),
                (
                    "publicado",
                    models.BooleanField(default=False, verbose_name="Publicado"),
                ),
                (
                    "reproducciones",
                    models.IntegerField(default=0, verbose_name="Reproducciones"),
                ),
                ("likes", models.IntegerField(default=0, verbose_name="Likes")),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="canciones",
                        to="admin.album",
                        verbose_name="Álbum",
                    ),
                ),
                (
                    "artista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canciones",
                        to="admin.artist",
                        verbose_name="Artista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Canción",
                "verbose_name_plural": "Canciones",
                "ordering": ["-fecha_subida"],
            },
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la Playlist"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                ("publica", models.BooleanField(default=True, verbose_name="Pública")),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Creador",
                    ),
                ),
                (
                    "canciones",
                    models.ManyToManyField(
                        blank=True,
                        related_name="playlists",
                        to="admin.song",
                        verbose_name="Canciones",
                    ),
                ),
            ],
            options={
                "verbose_name": "Playlist",
                "verbose_name_plural": "Playlists",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Play",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_hora",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y Hora"
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reproducciones",
                        to="users.sede",
                        verbose_name="Sede",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reproducciones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "cancion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reproducciones_registradas",
                        to="admin.song",
                        verbose_name="Canción",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reproducción",
                "verbose_name_plural": "Reproducciones",
                "ordering": ["-fecha_hora"],
            },
        ),
    ]
