# Generated by Django 5.2.8 on 2025-12-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="portada",
        ),
        migrations.AlterField(
            model_name="song",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portadas/",
                verbose_name="Imagen de Portada",
            ),
        ),
    ]
