# Generated by Django 5.2.8 on 2025-12-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0002_remove_album_portada_alter_song_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="portada",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="URL de Portada"
            ),
        ),
    ]
